from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm, mm
    from reportlab.platypus import (
        BaseDocTemplate,
        Frame,
        HRFlowable,
        PageBreak,
        PageTemplate,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    _HAS_REPORTLAB = True
except Exception:  # pragma: no cover
    _HAS_REPORTLAB = False

# ── Color Palette (matches InsightAI frontend) ──────────────────────────────

_NAVY = colors.HexColor("#0f1f44")
_BLUE = colors.HexColor("#4f6ef7")
_BLUE_LIGHT = colors.HexColor("#eef3ff")
_BLUE_SOFTER = colors.HexColor("#f5f8ff")
_GREEN = colors.HexColor("#10b981")
_AMBER = colors.HexColor("#f59e0b")
_RED = colors.HexColor("#ef4444")
_GRAY = colors.HexColor("#64748b")
_WHITE = colors.white
_ROW_ALT = colors.HexColor("#f8fafc")


# ── Custom Styles ────────────────────────────────────────────────────────────

def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "cover_title": ParagraphStyle(
            "CoverTitle", parent=base["Title"],
            fontName="Helvetica-Bold", fontSize=28, leading=34,
            textColor=_NAVY, alignment=TA_CENTER, spaceAfter=8,
        ),
        "cover_subtitle": ParagraphStyle(
            "CoverSubtitle", parent=base["Normal"],
            fontName="Helvetica", fontSize=14, leading=20,
            textColor=_GRAY, alignment=TA_CENTER, spaceAfter=24,
        ),
        "section_title": ParagraphStyle(
            "SectionTitle", parent=base["Heading1"],
            fontName="Helvetica-Bold", fontSize=16, leading=22,
            textColor=_NAVY, spaceBefore=18, spaceAfter=10,
        ),
        "subsection": ParagraphStyle(
            "Subsection", parent=base["Heading2"],
            fontName="Helvetica-Bold", fontSize=12, leading=16,
            textColor=_BLUE, spaceBefore=12, spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "BodyCustom", parent=base["BodyText"],
            fontName="Helvetica", fontSize=10, leading=14,
            textColor=colors.HexColor("#334155"), spaceAfter=6,
        ),
        "bullet": ParagraphStyle(
            "BulletCustom", parent=base["BodyText"],
            fontName="Helvetica", fontSize=10, leading=14,
            textColor=colors.HexColor("#334155"), leftIndent=20,
            bulletIndent=8, spaceAfter=4,
        ),
        "footer": ParagraphStyle(
            "Footer", parent=base["Normal"],
            fontName="Helvetica", fontSize=8, leading=10,
            textColor=_GRAY, alignment=TA_CENTER,
        ),
        "metric_label": ParagraphStyle(
            "MetricLabel", parent=base["Normal"],
            fontName="Helvetica", fontSize=9, leading=12,
            textColor=_GRAY,
        ),
        "metric_value": ParagraphStyle(
            "MetricValue", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=14, leading=18,
            textColor=_NAVY,
        ),
        "table_header": ParagraphStyle(
            "TableHeader", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=9, leading=12,
            textColor=_WHITE,
        ),
        "table_cell": ParagraphStyle(
            "TableCell", parent=base["Normal"],
            fontName="Helvetica", fontSize=8.5, leading=11,
            textColor=colors.HexColor("#1e293b"),
        ),
    }


# ── Header / Footer Drawing ─────────────────────────────────────────────────

def _header_footer(canvas, doc):
    canvas.saveState()
    width, height = A4
    # Header line
    canvas.setStrokeColor(_BLUE)
    canvas.setLineWidth(2)
    canvas.line(30, height - 35, width - 30, height - 35)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(_NAVY)
    canvas.drawString(30, height - 28, "InsightAI — Data Intelligence Report")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(_GRAY)
    canvas.drawRightString(width - 30, height - 28, datetime.now().strftime("%B %d, %Y"))

    # Footer
    canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
    canvas.setLineWidth(0.5)
    canvas.line(30, 30, width - 30, 30)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_GRAY)
    canvas.drawString(30, 18, "Generated by InsightAI — Autonomous Data Intelligence Engine")
    canvas.drawRightString(width - 30, 18, f"Page {doc.page}")
    canvas.restoreState()


# ── Table Helpers ────────────────────────────────────────────────────────────

def _styled_table(data: list[list], col_widths: list[float] | None = None) -> Table:
    table = Table(data, colWidths=col_widths, repeatRows=1)
    style_commands = [
        # Header
        ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), _WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        # Body
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8.5),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        # Grid
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    # Alternating row colors
    for i in range(1, len(data)):
        bg = _BLUE_SOFTER if i % 2 == 0 else _WHITE
        style_commands.append(("BACKGROUND", (0, i), (-1, i), bg))
    table.setStyle(TableStyle(style_commands))
    return table


def _section_divider() -> HRFlowable:
    return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=8, spaceBefore=4)


# ── PDF Builder ──────────────────────────────────────────────────────────────

def _build_pdf(
    df: pd.DataFrame,
    report_path: Path,
    summary: dict[str, Any],
    statistics: dict[str, Any],
    insights: list[str],
    model_results: dict[str, Any] | None = None,
) -> Path:
    styles = _build_styles()
    width, height = A4
    margin = 30

    doc = BaseDocTemplate(
        str(report_path),
        pagesize=A4,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=50,
        bottomMargin=50,
    )
    frame = Frame(margin, 50, width - 2 * margin, height - 100, id="main")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_header_footer)])

    story: list = []

    # ── Cover Page ───────────────────────────────────────────────────────
    story.append(Spacer(1, 80))
    story.append(Paragraph("InsightAI", styles["cover_title"]))
    story.append(Paragraph("Data Intelligence Report", styles["cover_subtitle"]))
    story.append(Spacer(1, 30))
    story.append(_section_divider())
    story.append(Spacer(1, 20))

    # Key metrics grid on cover
    overview = statistics.get("overview", summary) if statistics else summary
    quality = statistics.get("data_quality", {}) if statistics else {}
    quality_score = quality.get("overall", "N/A")

    cover_data = [
        ["Metric", "Value"],
        ["Dataset", str(summary.get("filename", "—"))],
        ["Total Records", f"{overview.get('rows', 0):,}"],
        ["Feature Dimensions", f"{overview.get('columns', 0)} columns"],
        ["Numeric Features", str(overview.get("numeric_columns", 0))],
        ["Categorical Features", str(overview.get("categorical_columns", 0))],
        ["Data Quality Score", f"{quality_score}%"],
        ["Report Generated", datetime.now().strftime("%B %d, %Y at %H:%M")],
    ]
    story.append(_styled_table(cover_data, col_widths=[200, 300]))
    story.append(PageBreak())

    # ── Executive Summary ────────────────────────────────────────────────
    story.append(Paragraph("1. Executive Summary", styles["section_title"]))
    story.append(_section_divider())

    exec_text = (
        f"This report presents an autonomous analysis of the uploaded dataset containing "
        f"<b>{overview.get('rows', 0):,}</b> records across <b>{overview.get('columns', 0)}</b> feature dimensions. "
        f"The data was automatically cleaned, validated, and analyzed by InsightAI's autonomous engine."
    )
    story.append(Paragraph(exec_text, styles["body"]))
    story.append(Spacer(1, 8))

    if insights:
        story.append(Paragraph("Key Findings:", styles["subsection"]))
        for i, insight in enumerate(insights[:8], 1):
            # Escape any HTML-like characters in the insight text
            safe_insight = str(insight).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(f"<b>{i}.</b> {safe_insight}", styles["bullet"]))
        story.append(Spacer(1, 12))

    # ── Data Quality Audit ───────────────────────────────────────────────
    story.append(Paragraph("2. Data Quality Audit", styles["section_title"]))
    story.append(_section_divider())

    quality_data = [
        ["Quality Dimension", "Score", "Status"],
        ["Completeness", f"{quality.get('completeness', 100)}%",
         "Excellent" if quality.get("completeness", 100) >= 95 else "Needs Attention"],
        ["Uniqueness", f"{quality.get('uniqueness', 100)}%",
         "Excellent" if quality.get("uniqueness", 100) >= 95 else "Needs Attention"],
        ["Consistency", f"{quality.get('consistency', 100)}%",
         "Excellent" if quality.get("consistency", 100) >= 90 else "Needs Attention"],
        ["Overall Score", f"{quality_score}%",
         "Excellent" if isinstance(quality_score, (int, float)) and quality_score >= 90 else "Good"],
    ]
    story.append(_styled_table(quality_data, col_widths=[180, 120, 200]))
    story.append(Spacer(1, 10))

    story.append(Paragraph(
        f"Missing cells: <b>{quality.get('missing_cells', 0):,}</b> out of {quality.get('total_cells', 0):,} "
        f"({quality.get('completeness', 100):.1f}% complete). "
        f"Duplicate rows: <b>{quality.get('duplicate_rows', 0):,}</b>.",
        styles["body"],
    ))

    # ── Statistical Analysis ─────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("3. Statistical Analysis", styles["section_title"]))
    story.append(_section_divider())

    numeric = statistics.get("numeric", {}) if statistics else {}
    if numeric:
        story.append(Paragraph("Numeric Feature Statistics", styles["subsection"]))
        num_headers = ["Column", "Mean", "Median", "Std Dev", "Min", "Max", "Skewness"]
        num_rows = [num_headers]
        for col_name, col_stats in list(numeric.items())[:20]:
            num_rows.append([
                str(col_name)[:20],
                f"{col_stats.get('mean', 0):.2f}",
                f"{col_stats.get('median', 0):.2f}",
                f"{col_stats.get('std_dev', 0):.2f}",
                f"{col_stats.get('min', 0):.2f}",
                f"{col_stats.get('max', 0):.2f}",
                f"{col_stats.get('skewness', 0):.3f}",
            ])
        story.append(_styled_table(num_rows, col_widths=[90, 68, 68, 68, 68, 68, 68]))
        story.append(Spacer(1, 12))

    categorical = statistics.get("categorical", {}) if statistics else {}
    if categorical:
        story.append(Paragraph("Categorical Feature Statistics", styles["subsection"]))
        cat_headers = ["Column", "Unique Values", "Most Common", "Frequency", "Null %"]
        cat_rows = [cat_headers]
        for col_name, col_stats in list(categorical.items())[:15]:
            cat_rows.append([
                str(col_name)[:20],
                str(col_stats.get("unique_count", 0)),
                str(col_stats.get("most_common", ""))[:20],
                str(col_stats.get("most_common_count", 0)),
                f"{col_stats.get('null_pct', 0):.1f}%",
            ])
        story.append(_styled_table(cat_rows, col_widths=[100, 90, 140, 80, 70]))
        story.append(Spacer(1, 12))

    # ── Correlation Analysis ─────────────────────────────────────────────
    correlation = statistics.get("correlation", {}) if statistics else {}
    top_pairs = correlation.get("top_pairs", [])
    if top_pairs:
        story.append(Paragraph("4. Correlation Analysis", styles["section_title"]))
        story.append(_section_divider())
        story.append(Paragraph("Top Correlated Feature Pairs", styles["subsection"]))
        corr_headers = ["Feature A", "Feature B", "Correlation", "Strength"]
        corr_rows = [corr_headers]
        for pair in top_pairs[:10]:
            corr_rows.append([
                str(pair.get("col_a", ""))[:20],
                str(pair.get("col_b", ""))[:20],
                f"{pair.get('value', 0):.4f}",
                str(pair.get("strength", "")).capitalize(),
            ])
        story.append(_styled_table(corr_rows, col_widths=[130, 130, 100, 100]))
        story.append(Spacer(1, 12))

    # ── Anomaly Detection ────────────────────────────────────────────────
    anomalies = statistics.get("anomaly_summary", {}) if statistics else {}
    if anomalies:
        story.append(Paragraph("5. Anomaly Detection", styles["section_title"]))
        story.append(_section_divider())
        anom_headers = ["Column", "Outliers", "% of Total", "Severity", "Lower Bound", "Upper Bound"]
        anom_rows = [anom_headers]
        for col_name, anom_data in list(anomalies.items())[:15]:
            anom_rows.append([
                str(col_name)[:20],
                str(anom_data.get("outlier_count", 0)),
                f"{anom_data.get('outlier_pct', 0):.1f}%",
                str(anom_data.get("severity", "")).capitalize(),
                f"{anom_data.get('lower_bound', 0):.2f}",
                f"{anom_data.get('upper_bound', 0):.2f}",
            ])
        story.append(_styled_table(anom_rows))
        story.append(Spacer(1, 12))

    # ── Data Preview ─────────────────────────────────────────────────────
    story.append(PageBreak())
    section_num = 6 if anomalies else 5
    story.append(Paragraph(f"{section_num}. Dataset Preview (First 20 Rows)", styles["section_title"]))
    story.append(_section_divider())

    preview_cols = list(df.columns)[:8]  # Limit to 8 columns for page width
    preview_rows = [preview_cols]
    for _, row in df[preview_cols].head(20).iterrows():
        preview_rows.append([str(val)[:18] if pd.notna(val) else "—" for val in row])

    if len(preview_rows) > 1:
        col_w = max(60, min(120, int(500 / len(preview_cols))))
        story.append(_styled_table(preview_rows, col_widths=[col_w] * len(preview_cols)))

    # ── Model Results (if available) ─────────────────────────────────────
    if model_results and model_results.get("best_model"):
        story.append(PageBreak())
        story.append(Paragraph(f"{section_num + 1}. Machine Learning Results", styles["section_title"]))
        story.append(_section_divider())
        story.append(Paragraph(
            f"Best performing model: <b>{model_results['best_model']}</b> "
            f"(Score: {model_results.get('best_score', 0):.4f})",
            styles["body"],
        ))

    # ── Footer Note ──────────────────────────────────────────────────────
    story.append(Spacer(1, 30))
    story.append(_section_divider())
    story.append(Paragraph(
        "This report was autonomously generated by InsightAI Autonomous Data Intelligence Engine. "
        "All statistics and machine learning metrics are computed from the cleaned and validated dataset.",
        styles["body"],
    ))

    doc.build(story)
    return report_path


# ── Public API ───────────────────────────────────────────────────────────────

def export_report(
    df: pd.DataFrame,
    report_path: Path,
    format_name: str,
    summary: dict[str, Any],
    statistics: dict[str, Any],
    insights: list[str],
    model_results: dict[str, Any] | None = None,
) -> Path:
    report_path.parent.mkdir(parents=True, exist_ok=True)

    if format_name == "csv":
        # Export actual cleaned data as CSV
        df.to_csv(report_path, index=False)
        return report_path

    if format_name == "excel":
        overview = statistics.get("overview", summary) if statistics else summary
        numeric_stats = statistics.get("numeric", {}) if statistics else {}
        categorical_stats = statistics.get("categorical", {}) if statistics else {}

        with pd.ExcelWriter(report_path) as writer:
            # Summary sheet
            pd.DataFrame([overview]).to_excel(writer, index=False, sheet_name="Summary")

            # Numeric statistics sheet
            if numeric_stats:
                num_df = pd.DataFrame(numeric_stats).T
                num_df.index.name = "Column"
                num_df.to_excel(writer, sheet_name="Numeric Stats")

            # Categorical statistics sheet
            if categorical_stats:
                cat_data = []
                for col, stats in categorical_stats.items():
                    cat_data.append({
                        "Column": col,
                        "Unique Count": stats.get("unique_count", 0),
                        "Most Common": stats.get("most_common", ""),
                        "Most Common Count": stats.get("most_common_count", 0),
                        "Null %": stats.get("null_pct", 0),
                    })
                pd.DataFrame(cat_data).to_excel(writer, index=False, sheet_name="Categorical Stats")

            # Insights sheet
            if insights:
                pd.DataFrame({"AI Insight": insights}).to_excel(writer, index=False, sheet_name="AI Insights")

            # Correlation sheet
            correlation = statistics.get("correlation", {}) if statistics else {}
            corr_matrix = correlation.get("matrix", [])
            corr_cols = correlation.get("columns", [])
            if corr_matrix and corr_cols:
                corr_df = pd.DataFrame(corr_matrix, columns=corr_cols, index=corr_cols)
                corr_df.to_excel(writer, sheet_name="Correlation Matrix")

            # Data Preview sheet
            df.head(200).to_excel(writer, index=False, sheet_name="Data Preview")

        return report_path

    # PDF
    if _HAS_REPORTLAB:
        return _build_pdf(df, report_path, summary, statistics, insights, model_results)

    # Fallback: text
    fallback = report_path.with_suffix(".txt")
    lines = [
        "=" * 60,
        "InsightAI — Data Intelligence Report",
        "=" * 60,
        f"\nGenerated: {datetime.now().strftime('%B %d, %Y at %H:%M')}\n",
        f"Summary: {summary}\n",
        f"Statistics: {statistics}\n",
        "Insights:",
    ]
    for i, insight in enumerate(insights, 1):
        lines.append(f"  {i}. {insight}")
    fallback.write_text("\n".join(lines), encoding="utf-8")
    return fallback
